
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test_vop.exe is a Catch v2.10.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
vector sample produces properly-size result container
  sampled container size is a perfect multiple of the sample stride
-------------------------------------------------------------------------------
C:\SVC\zhu48\led_strip\test\test_vop.cpp(118)
...............................................................................

C:\SVC\zhu48\led_strip\test\test_vop.cpp(124): FAILED:
  CHECK( result.size() == 4 )
with expansion:
  3 == 4

-------------------------------------------------------------------------------
vector sample produces properly-size result container
  sampled container size is a perfect multiple of the sample stride plus one
-------------------------------------------------------------------------------
C:\SVC\zhu48\led_strip\test\test_vop.cpp(126)
...............................................................................

C:\SVC\zhu48\led_strip\test\test_vop.cpp(132): FAILED:
  CHECK( result.size() == 4 )
with expansion:
  3 == 4

-------------------------------------------------------------------------------
vector sample produces proper sample array
  sampled container size is a perfect multiple of the sample stride
-------------------------------------------------------------------------------
C:\SVC\zhu48\led_strip\test\test_vop.cpp(137)
...............................................................................

C:\SVC\zhu48\led_strip\test\test_vop.cpp(146): FAILED:
  CHECK( result.at( 3 ) == 7 )
due to unexpected exception with message:
  invalid vector<T> subscript

-------------------------------------------------------------------------------
vector sample produces proper sample array
  sampled container size is a perfect multiple of the sample stride plus one
-------------------------------------------------------------------------------
C:\SVC\zhu48\led_strip\test\test_vop.cpp(148)
...............................................................................

C:\SVC\zhu48\led_strip\test\test_vop.cpp(157): FAILED:
  CHECK( result.at( 3 ) == 10 )
due to unexpected exception with message:
  invalid vector<T> subscript

===============================================================================
test cases:  6 |  4 passed | 2 failed
assertions: 42 | 38 passed | 4 failed

